name: Manual2
on:
  workflow_dispatch:
    inputs:
      env:
        description: Target
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.env }}"